### ISSUE TITLE
Why do you need a menu and pause menu?

### ISSUE THREAD

**Issue by SirElismyer** [epai/tetris-terminal-game#1]
If "m" menu effectively pauses the game but "p" pause does not give ability to access menu items, does it not make more sense to just put the menu options in the "p" pause menu and get rid of the "m" pause menu all together?

**Comment by epai** [comment]
Great point!  You’re right - the pause and menu screens can be combined to simplify the logic

**Comment by epai** [comment]
Thanks for the issue; I’m thinking about refactoring the code base one day (I made this freshman year of college years ago), but if you’d like to contribute feel free to make a pull request!

**Comment by SirElismyer** [comment]
Thanks! I'm trying to learn Python and your code is just past my experience at this point (I'm Googling a ton - especially curse commands) but I think I get the gist. If I come across something I'll be sure to pull!

**Comment by epai** [comment]
That’s awesome man!  Python is a great language.  Let me know if you have any questions :). (Disclaimer:  the GUI code is hella jank and hard-coded.  You have been warned!)

**Comment by epai** [comment]
Resolved by #2
